import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  viewTextAdd: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewBtn: {
    height: 50,
    borderRadius: 50 / 2,
    paddingHorizontal: 10,
    backgroundColor: '#6600e7',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  btnLocAdd: {
    alignSelf: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  viewRenderItem: {
    flexDirection: 'row',
    alignItems: 'center',
    margin: 20,
    maxWidth: 480,
    alignSelf: 'center',
  },
  textEmptyComponent: {
    textAlign: 'center',
    color: 'grey',
    fontSize: 17,
    top: 30,
  },
  textEdit: {
    color: 'white',
    fontWeight: '500',
    fontSize: 16,
  },
  btnEdit: {
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    backgroundColor: '#6600E7',
    width: 100,
    height: 35,
    borderRadius: 15,
    elevation: 5,
    paddingVertical: 5,
    overflow: 'hidden',
  },
  textInputModal: {
    borderBottomWidth: 1,
    width: '80%',
    alignSelf: 'center',
    paddingHorizontal: 10,
    color: 'black',
  },
  headerModal: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  viewModal: {
    backgroundColor: 'white',
    width: '80%',
    padding: 20,
    borderRadius: 15,
    elevation: 5,
    maxWidth: 480,
  },
  modalContainer: {
    justifyContent: 'center',
    flex: 1,
    alignItems: 'center',
    // maxWidth: 480,
  },
  backDrop: {
    backgroundColor: 'black',
    width: '100%',
    height: '100%',
    opacity: 0.35,
    position: 'absolute',
  },
  viewLine: {
    backgroundColor: 'grey',
    width: 2,
    height: 50,
    marginHorizontal: 10,
  },
  btnTugas: {
    backgroundColor: '#6600E7',
    width: 30,
    height: 30,
    borderRadius: 5,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewBtnCollapse: {
    backgroundColor: '#a1a1a1',
    width: 25,
    height: 25,
    borderRadius: 25 / 2,
  },
  textDeskripsi: {
    fontSize: 15,
    fontWeight: '500',
  },
  textTugas: {
    fontSize: 18,
    fontWeight: '700',
    color: 'black',
  },
  viewTugas: {
    backgroundColor: 'white',
    flexDirection: 'row',
    padding: 20,
    borderRadius: 20,
    flex: 1,
    alignItems: 'center',
    elevation: 5,
  },
  viewInputPlus: {
    flexDirection: 'row',
    marginTop: 20,
    margin: 10,
    maxWidth: 600,
    alignSelf: 'center',
  },
  btnAdd: {
    backgroundColor: '#6600E7',
    borderRadius: 50 / 2,
    alignItems: 'center',
    width: 50,
    height: 50,
    elevation: 5,
    justifyContent: 'center',
  },
  textInput: {
    backgroundColor: 'white',
    borderRadius: 50 / 2,
    height: 50,
    paddingHorizontal: 20,
    elevation: 5,
    flexDirection: 'row',
    flex: 1,
  },
  textHeader: {
    fontSize: 25,
    fontWeight: 'bold',
    color: 'white',
    paddingHorizontal: 10,
  },
  viewHeader: {
    flexDirection: 'row',
    backgroundColor: '#6600E7',
    height: 60,
    elevation: 5,
    alignItems: 'center',
    paddingHorizontal: 20,
  },
});

export default styles;
